### ISSUE TITLE
clickout.js:24 Uncaught: key is not defined

### ISSUE THREAD

**Issue by wallacemaxters** [alexshink/vue3-clickaway#2]
When used object as parameters like with `{event: callback, active: true}`, the error bellow as ocurred:

```clickout.js:24 Uncaught: key is not defined```

The problem is caused by this line in `clickout.js`:

```javascript
if ( typeof args === 'object' ) {
    for (key in params) {
         // Arguments 'require' checking
```

The Javascript requires the `let` ou `var` keyword in this line.

**Comment by alexshink** [comment]
Hello. it really is, my mistake, thanks a lot. Will be fixed within a few hours.

**Comment by alexshink** [comment]
781dad8:
• fixing variable declaration in params
• changed version in NPM to 1.1.1

Please update the package. If everything is alright, I'll close this issue.

**Comment by wallacemaxters** [comment]
Thanks!
